apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: post-only
  namespace: ${ECS_CLUSTER_NS}
spec:
  targetRefs:
  - kind: Gateway
    group: gateway.networking.k8s.io
    name: waypoint
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: ["default", "$ECS_CLUSTER_NS"]
    to:
    - operation:
        methods: ["POST"]
